# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v2
    - name: Install Platform Dependencies
      run: |
        sudo apt install -y xvfb x11-utils libxkbcommon-x11-0 # https://stackoverflow.com/questions/60692711/cant-create-python-qapplication-in-github-action
        sudo apt install -y libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0  # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install .[dev,ci]
    - name: Test with pytest, tracking coverage
      env:
        QT_DEBUG_PLUGINS: 1
      run: |
        echo $DISPLAY
        coverage run -m pytest -m "not buggyci"
    - name: Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pip install coverage[toml]
        pip install coveralls
        coveralls
